# Maven CI/CD Pipeline Test

trigger:
- master  # Triggers on changes to the master branch

pool:
  vmImage: ubuntu-latest  # Using the latest Ubuntu image

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your POM file
    mavenOptions: '-Xmx3072m'  # JVM memory allocation for Maven
    javaHomeOption: 'JDKVersion'  # Use the specified JDK version
    jdkVersionOption: '11'  # Specify JDK 11
    jdkArchitectureOption: 'x64'  # Specify x64 architecture
    publishJUnitResults: true  # Publish JUnit test results
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Path to JUnit results
    goals: 'package'  # Maven goal to execute

- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'  # Files to copy (change this if your output is not .war)
    TargetFolder: '$(build.artifactStagingDirectory)'  # Where to copy the files

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'  # Path to publish
    ArtifactName: 'warFile'  # Name of the artifact
    publishLocation: 'Container'  # Publish location type
