# Build your Java project and run tests with Apache Maven.
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Run Maven with updated version
- task: Maven@4  # Updated from Maven@3 to Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-X -e -Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# Copy WAR file
- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'

# List the contents of the build directory for debugging
- script: |
    echo "Contents of the build directory:"
    ls -R $(Build.SourcesDirectory)
  displayName: 'List contents of build directory'

# Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warFile'
    publishLocation: 'Container'

# Deploy to Azure App Service (in the release pipeline)
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial (2cee8c2c-05e3-45f6-b58b-38bde49e1643)'
    appType: 'webApp'
    appName: 'ashwinkallingal'
    package: '$(Pipeline.Workspace)/**/*.war'  # Use this updated path
