# Maven
# Build your Java project and run tests with Apache Maven.
# CI/CD Pipeline

trigger:
  branches:
    include:
      - master

pool:
  vmImage: ubuntu-latest

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '12'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'

- task: CopyFiles@2
  inputs:
    contents: '**/*.war'
    targetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactstagingdirectory)'
    artifactName: 'warFile'
    publishLocation: 'Container'
