# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# Cross CI

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Install Google Chrome
- script: |
    sudo apt-get update
    sudo apt-get install -y google-chrome-stable
  displayName: 'Install Google Chrome'

# Install ChromeDriver
- script: |
    CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
    CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
    if [ -z "$CHROMEDRIVER_VERSION" ]; then
      echo "Failed to fetch ChromeDriver version. Exiting."
      exit 1
    fi
    curl -O https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
    if [ ! -f chromedriver_linux64.zip ]; then
      echo "Failed to download ChromeDriver. Exiting."
      exit 1
    fi
    unzip chromedriver_linux64.zip -d /usr/local/bin/
    chmod +x /usr/local/bin/chromedriver
  displayName: 'Install ChromeDriver'

# Build and run tests with Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# Copy WAR files to artifact staging directory
- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'

# Publish build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warFile'
    publishLocation: 'Container'
