# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
# Crosscheck CI/CD Components Checked

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Install JDK 11 if necessary
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'  # Added this input
  displayName: 'Install JDK 11'

# Check Java and Maven versions
- script: |
    java -version
    mvn -v
  displayName: 'Check Java and Maven Version'

# Run Maven
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-X -e -Xmx3072m'  # Added debug options
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'  # Ensure this matches your requirements
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# Copy WAR file
- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(build.artifactstagingdirectory)'

# List contents of the artifact staging directory
- script: |
    echo "Listing contents of the artifact staging directory:"
    ls $(build.artifactstagingdirectory)
  displayName: 'List Artifact Staging Directory Contents'

# Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warFile'
    publishLocation: 'Container'

# Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial (2cee8c2c-05e3-45f6-b58b-38bde49e1643)'
    appType: 'webApp'
    appName: 'ashwinkallingal'
    package: '$(System.DefaultWorkingDirectory)/warFile/**/*.war'  # Updated to reflect the path for the WAR file
