# Build your Java project and run tests with Apache Maven.
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
# Run Maven with updated version
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-X -e -Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'  # Added clean to ensure a fresh build

# List the contents of the target directory for debugging
- script: |
    echo "Contents of the target directory after Maven build:"
    ls -R target || echo "Target directory does not exist."
  displayName: 'List contents of target directory'

# Copy WAR file
- task: CopyFiles@2
  inputs:
    Contents: 'target/**/*.war'  # Adjusting to target directory where WAR is usually built
    TargetFolder: '$(build.artifactstagingdirectory)'

# List the contents of the artifact staging directory for debugging
- script: |
    echo "Contents of the artifact staging directory:"
    ls -R $(Build.ArtifactStagingDirectory) || echo "Artifact staging directory does not exist."
  displayName: 'List contents of artifact staging directory'

# Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warFile'
    publishLocation: 'Container'

# Deploy to Azure App Service (in the release pipeline)
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial (2cee8c2c-05e3-45f6-b58b-38bde49e1643)'
    appType: 'webApp'
    appName: 'ashwinkallingal'
    package: '$(Build.ArtifactStagingDirectory)/**/*.war'  # Use the correct path here
