trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  javaVersion: '11'  # Set the required Java version

steps:
# Step 1: Install Java version
- task: JavaToolInstaller@0
  inputs:
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'  # Can be 'PreInstalled' or 'AzureStorage' for a custom source
  displayName: 'Install Java version'

# Step 2: Check Java version
- script: java -version
  displayName: 'Check Java version'

# Step 3: Maven Build
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'
  displayName: 'Maven Build'

# Step 4: Copy WAR File to Artifact Staging Directory
- task: CopyFiles@2
  inputs:
    contents: '**/*.war'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy WAR File to Staging Directory'

# Step 5: Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warfile'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'

# Step 6: Deploy to Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial (2cee8c2c-05e3-45f6-b58b-38bde49e1643)'
    appName: 'ashwinkallingal'
    package: '$(Build.ArtifactStagingDirectory)/**/*.war'
  displayName: 'Deploy to Azure App Service'
